[project]
name = "builder"
version = "0.1.0"
description = "Builder for my blog."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "markdown>=3.8.2",
]

[project.scripts]
site = "builder.cli:build"

[tool.uv]
package = true


